version: '3.8'
services:

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=manager
    ports:
      - "5550:5550"
    networks:
      app_net:
        ipv4_address: 192.168.0.2
    volumes:
      - ./data/db:/var/lib/postgresql/data
    build:
      context: .
      dockerfile: app/bd.Dockerfile

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@dom.ru"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    depends_on:
      - postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1
